exclude:
  # Ignore the recently added directories with binaries to avoid going over the 10 GB limit in our
  # GH pages. Serve only the pre-existing bin/ and wasm/ to keep old links to GH pages working.
  - emscripten-asmjs
  - emscripten-wasm32
  - linux-amd64
  - macosx-amd64
  - windows-amd64
